# Skeleton Homebrew formula for Sotto. The real, resource-filled copy lives in
# the tap repo (tomoima525/homebrew-sotto) as Formula/sotto.rb. This copy is
# kept in-repo for review and reproducibility; see ./README.md for how the
# `resource` blocks are generated and kept up to date.
#
# Apple Silicon only (MLX has no Intel build). sounddevice bundles its own
# PortAudio, so no system audio dependency is required.
class Sotto < Formula
  include Language::Python::Virtualenv

  desc "Fully-local dictation for macOS: hotkey to speak, get cleaned text"
  homepage "https://github.com/tomoima525/sotto"
  url "https://github.com/tomoima525/sotto/archive/refs/tags/1.0.2.tar.gz"
  # Placeholder: replace with the real tarball sha256 at release time
  # (see ./README.md). 64 zeros keeps `brew style` quiet for the skeleton.
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  license "MIT"

  depends_on arch: :arm64
  depends_on :macos
  depends_on "python@3.12"

  # >>> resources generated by `brew update-python-resources sotto` <<<
  # (mlx, mlx-whisper, mlx-lm, transformers, tokenizers, safetensors, numpy,
  #  huggingface-hub, rumps, sounddevice, the pyobjc-* frameworks, and all
  #  transitive deps land here. Many are wheel resources — expected on arm64.)

  def install
    virtualenv_install_with_resources
  end

  test do
    # Exercises the CLI without needing a mic, models, or TCC permissions.
    assert_match "usage: sotto", shell_output("#{bin}/sotto --help")
    assert_match version.to_s, shell_output("#{bin}/sotto --version")
  end
end
